name = "BP_MAP"
authors = ["Luiz-Rafael Santos", "Paulo J. S. Silva", "Roger Behling", "Yunier Bello-Cruz"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"

[compat]
DrWatson = "2.14.1"
julia = "1.10.2"
